---
## Kubernetes
## ********************************************************************************************************************************
k8s_master_counts: "{{ groups['kube-master'] | length }}"
all_nodes_counts: "{{ groups['all'] | length }}"

k8s_master_apiservice_bind_port: 5443
k8s_cluster_ip: '10.96.0.1'
k8s_cluster_ip_range: '10.96.0.0/12'
k8s_load_balance_ip: 192.168.1.201

k8s_apiserver_https_bind: 'https://{{ k8s_load_balance_ip }}:6443'
k8s_apiserver_node_port_range: '30000-32767'

is_kube_master: "{{ inventory_hostname in groups['kube-master'] }}"
is_kube_node: "{{ inventory_hostname in groups['kube-node'] }}"
is_load_images: false
is_kube_master_schedule: true
is_using_local_files: false

k8s_master_ip_list: >-
  [{% for host in groups['kube-master'] -%}
    '{{ hostvars[host].ansible_default_ipv4.address }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

k8s_master_name_list: >-
  [{% for host in groups['kube-master'] -%}
    '{{ hostvars[host].ansible_nodename }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

k8s_master_ip_str: >-
  {% for host in groups['kube-master'] -%}
    {{ hostvars[host].ansible_default_ipv4.address }}
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}

k8s_master_name_str: >-
  {% for host in groups['kube-master'] -%}
    {{ hostvars[host].ansible_nodename }}
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}

k8s_node_ip_list: >-
  [{% for host in groups['kube-node'] -%}
    '{{ hostvars[host].ansible_default_ipv4.address }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

k8s_node_name_list: >-
  [{% for host in groups['kube-node'] -%}
    '{{ hostvars[host].ansible_nodename }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

## Configuration Directory
## ********************************************************************************************************************************
kubernetes_ctl_path: '/usr/local/bin/'

etcd_ssl_dirs: '/etc/etcd/ssl/'

etcd_data_dirs: '/var/lib/etcd/'

kubernetes_pki_dirs: '{{ kubernetes_etc_dirs }}pki/'

kubernetes_etc_dirs: '/etc/kubernetes/'

kubernetes_manifests_dirs: '{{ kubernetes_etc_dirs }}manifests/'

kubernetes_cni_dirs: '/opt/cni/bin'

haproxy_etc_dirs: '/etc/haproxy/'

systemd_etc_dirs: '/etc/systemd/system/'

kubelet_work_dirs: '/var/lib/kubelet/'

temporary_dirs: '/tmp/'

## SSH
## ********************************************************************************************************************************
ssh_connect_user: "shilei"

ssh_connect_port: 22

ssh_public_key: "{{ target_ssh_private_key_file }}"

source_ssh_public_key_file: "{{ hostvars[inventory_hostname]['ansible_ssh_public_key_file'] }}"

source_ssh_private_key_file: "{{ hostvars[inventory_hostname]['ansible_ssh_private_key_file'] }}"

target_ssh_private_key_file: "{{ temporary_dirs }}.general-id_rsa"

## Keepalived
## ********************************************************************************************************************************
is_keepalived: false

keepalived_ip: "{{ k8s_load_balance_ip }}"

vip_bind_net_device: "{{ os_network_device_name }}"

## Etcd
## ********************************************************************************************************************************
#
os_network_device_name: 'ens4'

etcd_url_scheme: "https"

etcd_peer_url_scheme: "https"

etcd_client_cert_auth: true

etcd_peer_client_cert_auth: true

etcd_client_port: 2379

etcd_peer_port: 2380

etcd_interface: ""

is_etcd_master: "{{ inventory_hostname in groups['etcd'] }}"

etcd_master_ip_str: >-
  {% for host in groups['etcd'] -%}
    {{ hostvars[host].ansible_default_ipv4.address }}
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}

etcd_master_ip_list: >-
  [{% for host in groups['kube-master'] -%}
    '{{ hostvars[host].ansible_default_ipv4.address }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

etcd_initial_cluster_addr: >-
  {% for host in groups['etcd'] -%}
    {{ etcd_peer_url_scheme }}://
    {%- if etcd_interface != "" -%}
      {{ hostvars[host]['ansible_' + etcd_interface].ipv4.address }}
    {%- else -%}
      {{ hostvars[host].ansible_default_ipv4.address }}
    {%- endif -%}
  :{{ etcd_client_port }}
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}

## Add Nodes
## ********************************************************************************************************************************

add_node_ip_list: >-
  [{% for host in groups['k8s-cluster-add-node'] -%}
    '{{ hostvars[host].ansible_default_ipv4.address }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

add_node_name_list: >-
  [{% for host in groups['k8s-cluster-add-node'] -%}
    '{{ hostvars[host].ansible_nodename }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

add_master_ip_list: >-
  [{% for host in groups['k8s-cluster-add-master'] -%}
    '{{ hostvars[host].ansible_default_ipv4.address }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

add_master_name_list: >-
  [{% for host in groups['k8s-cluster-add-master'] -%}
    '{{ hostvars[host].ansible_nodename }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

is_add_master: "{{ inventory_hostname in groups['k8s-cluster-add-master'] }}"
is_add_node: "{{ inventory_hostname in groups['k8s-cluster-add-node'] }}"

## Clean Kubernetes Cluster
## ********************************************************************************************************************************

is_remove_docker_ce: false
