---

- name: Check OS Info
  setup:
  when: ansible_lsb.id == 'Ubuntu'

- name: Apt Update Source
  shell: apt update

- name: Apt Install Dependence
  shell: apt install -y apt-transport-https curl ca-certificates software-properties-common

- name: Apt Install Docker GPG
  shell: curl -fsSL {{ docker_ubuntu_repo_gpgkey }} | sudo apt-key add -

- name: Apt Configuration Docker Source And Update Apt Source
  shell: add-apt-repository "deb [arch=amd64] {{ docker_ubuntu_repo_base_url }} {{ os_system_codename }} stable" && apt update

- name: Apt Install Docker-ce
  shell: apt install -y docker-ce=$(apt-cache madison docker-ce | grep {{ docker_version }} | head -1 | awk '{print $3}')

- name: Docker-ce Powered UP And Startd
  service: 
    name: docker
    enabled: yes
- service:
    name: docker
    state: started

- name: Check Docker-ce Version
  shell: docker version
  register: result

- debug:
    var: result['stdout_lines']
    verbosity: 0  