---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Output current Ansible Version.
      shell: ansible --version || true

- hosts: k8s-cluster:etcd
  gather_facts: true
  sudo: yes
  remote_user: "{{ ssh_connect_user }}"
  roles:
    - { role: downloads-ssh-key, tags: [copy_ssh_private_key]}

- name: Prepare the environment and install docker.
  hosts: k8s-cluster:etcd
  sudo: yes
  remote_user: "{{ ssh_connect_user }}"
  vars:
    ansible_ssh_pipelining: true
  roles:
    - { role: clean-install, tags: [clean]}
    - { role: system-initialize, tags: [system]}
    - { role: docker-install, when: ansible_lsb.id == 'Ubuntu', tags: [docker]}

- name: Binary File Deployment.
  hosts: k8s-cluster:etcd
  sudo: yes
  remote_user: "{{ ssh_connect_user }}"
  vars:
    ansible_ssh_pipelining: true
  roles:
    - { role: downloads-packages, tags: [packages]}
  tasks:
    - { include: roles/kubernetes-default/includes/main.yml }

- name: Cluster Master Configuration File Deployment, CFSSL Generated CA
  hosts: kube-master[0]
  sudo: yes
  remote_user: "{{ ssh_connect_user }}"
  vars:
    ansible_ssh_pipelining: true
  roles:
    - { role: kubernetes-default, tags: [kubernetes]}

- name: Generate Etcd CA
  hosts: etcd[0]
  sudo: yes
  remote_user: "{{ ssh_connect_user }}"
  vars:
    ansible_ssh_pipelining: true
  tasks:
    - { include: roles/etcd-install/includes/main.yml }

- name: Copy Etcd Config
  hosts: etcd
  sudo: yes
  remote_user: "{{ ssh_connect_user }}"
  vars:
    ansible_ssh_pipelining: true
  roles:
    - { role: etcd-install, tags: [etcd]}

- name: Cluster Master Kubernetes Manifests Files
  hosts: kube-master
  sudo: yes
  remote_user: "{{ ssh_connect_user }}"
  vars:
    ansible_ssh_pipelining: true
  roles:
    - { role: kubernetes-manifests, tags: [manifests]}

- name: Create Kubernetes Kubelet Config and Run Kubelet
  hosts: kube-master
  gather_facts: true
  sudo: yes
  remote_user: "{{ ssh_connect_user }}"
  vars:
    ansible_ssh_pipelining: true
  tasks:
    - { include: roles/kubernetes-default/includes/kubelet_pem.yml }
    - name: Run Kubelet
      service:
        name: kubelet
        state: started
    - { include: roles/kubernetes-bootstraps/includes/admin.yml }

- name:  Add Kubernetes Apiserver to Kubelet and Bootstrap RBAC and Copy Nodes Config to Worker.
  hosts: kube-master[0]
  gather_facts: true
  sudo: yes
  remote_user: "{{ ssh_connect_user }}"
  vars:
    ansible_ssh_pipelining: true
  roles:
    - { role: kubernetes-bootstraps, tags: [bootstraps]}
  tasks:
    - { include: roles/kubernetes-nodes/includes/main.yml }

- name: Create Nodes
  hosts: kube-node
  gather_facts: true
  sudo: yes
  remote_user: "{{ ssh_connect_user }}"
  vars:
    ansible_ssh_pipelining: true
  roles:
    - { role: kubernetes-nodes, tags: [nodes]}

- name: Create Kubernetes Network
  hosts: kube-master[0]
  gather_facts: true
  sudo: yes
  remote_user: "{{ ssh_connect_user }}"
  vars:
    ansible_ssh_pipelining: true
  roles:
    - { role: kubernetes-networks, tags: [networks]}

# - name: Test
#   hosts: all[0]
#   # gather_facts: false
#   # sudo: yes
#   remote_user: "{{ ssh_connect_user }}"
#   vars:
#     ansible_ssh_pipelining: true
#   tasks:
#     - include: tests/includes/main.yml
