---
- name: Stop Kubelet
  service: 
    name: kubelet
    state: stopped
  ignore_errors: true

- name: Clean kubernetes Etc Working directory.
  shell: "rm -rf {{ kubernetes_etc_dirs }}"
  ignore_errors: true

- name: Clean Etcd Working directory.
  shell: "rm -rf {{ etcd_ssl_dirs }}"
  shell: "rm -rf {{ etcd_data_dirs }}"
  ignore_errors: true

- shell: "rm -rf {{ kubelet_work_dirs }}*"
  ignore_errors: true

- name: Clean Kubelet Working directory.
  shell: "rm -rf {{ kubelet_work_dirs }}*"
  ignore_errors: true

- name: Clean Docker Containers.
  shell: "docker rm -f $(docker ps -aq)"
  ignore_errors: true

- name: Clean Kubernet Ctl.
  shell: "rm -rf {{ kubernetes_ctl_path }}kubectl"
  shell: "rm -rf {{ kubernetes_ctl_path }}kubelet"
  ignore_errors: true

- name: Clean Tmp
  shell: "rm -rf {{ temporary_dirs }}kube*"
  ignore_errors: true

- name: Clean CNI
  shell: "rm -rf {{ kubernetes_cni_dirs }}"
  ignore_errors: true

- name: Clean Haproxy
  shell: "rm -rf {{ haproxy_etc_dirs }}"
  ignore_errors: true