---
# Kubernetes
## ********************************************************************************************************************************
- name: Copy Kubernetes CLi Binary Files
  copy:
    src: kubernetes/kubelet
    dest: /usr/local/bin/kubelet
    owner: "{{ ssh_connect_user }}"
    mode: 0755

- name: Copy Kubernetes Kubelet Binary Files
  copy:
    src: kubernetes/kubectl
    dest: /usr/local/bin/kubectl
    owner: "{{ ssh_connect_user }}"
    mode: 0755
  when: is_kube_master or is_add_master

- name: Create Kubernetes-cni workdir
  shell: mkdir -p /opt/cni/bin

- name: Copy Kubernetes-cni Plugin Binary Files
  copy:
    src: kubernetes-cni/cni-plugins-amd64-v0.6.0.tgz
    dest: /tmp/cni-plugins-amd64-v0.6.0.tgz
    owner: "{{ ssh_connect_user }}"
    mode: 0644

- name: Unzip Files
  shell: tar zxf /tmp/cni-plugins-amd64-v0.6.0.tgz -C /opt/cni/bin

# CFSSL
## ********************************************************************************************************************************
- name: Copy CFSSL Binary Files
  copy:
    src: cfssl/cfssl
    dest: /usr/local/bin/cfssl
    owner: "{{ ssh_connect_user }}"
    mode: 0755
  when: is_kube_master or is_add_master or is_etcd_master

- name: Copy CFSSL-JSON Binary Files
  copy:
    src: cfssl/cfssljson
    dest: /usr/local/bin/cfssljson
    owner: "{{ ssh_connect_user }}"
    mode: 0755
  when: is_kube_master or is_add_master or is_etcd_master

# Docker Image
# ********************************************************************************************************************************

- name: Copy Kubernetes Master of Docker Images
  copy:
    src: images/kubernetes-1.10_master-docker_image.tar
    dest: "{{ temporary_dirs }}kubernetes-1.10_master-docker_image.tar"
    owner: "{{ ssh_connect_user }}"
    mode: 0755
  when: (is_kube_master and is_load_images) or (is_add_master and is_load_images)
  ignore_errors: true
  
- name: Check Masters Image in Nodes
  shell: docker images -f reference=gcr.io/google_containers/kube-apiserver-amd64 | wc -l
  register: result

- shell: docker load -i {{ temporary_dirs }}kubernetes-1.10_master-docker_image.tar
  when: (is_kube_master and result.stdout|int < 2 and is_load_images) or
        (is_add_master and result.stdout|int < 2 and is_load_images)
  ignore_errors: true

- name: Copy Kubernetes Nodes of Docker Images
  copy:
    src: images/kubernetes-1.10_node-docker_image.tar
    dest: "{{ temporary_dirs }}kubernetes-1.10_node-docker_image.tar"
    owner: "{{ ssh_connect_user }}"
    mode: 0755
  when: (is_kube_node and is_load_images) or (is_add_node and is_load_images) 
  ignore_errors: true

- name: Check Worker Image in Nodes
  shell: docker images -f reference=k8s.gcr.io/pause-amd64 | wc -l
  register: result

- shell: docker load -i {{ temporary_dirs }}kubernetes-1.10_node-docker_image.tar
  when: (is_kube_node and result.stdout|int < 2 and is_load_images) or
        (is_add_node and result.stdout|int < 2 and is_load_images) 
  ignore_errors: true