---
# Etcd
## ********************************************************************************************************************************
- name: Copy CFSSL Etcd Json Files
  copy:
    src: cfssl-jsonfile/{{ item }}
    dest: "{{ etcd_ssl_dirs }}{{ item }}"
    owner: "{{ ssh_connect_user }}" 
    mode: 0644
  with_items:
    - ca-config.json
    - etcd-ca-csr.json
    - etcd-csr.json

# Kubernetes
## ********************************************************************************************************************************

- name: Copy CFSSL Kubernetes Json Files
  copy:
    src: cfssl-jsonfile/{{ item }}
    dest: "{{ kubernetes_pki_dirs }}{{ item }}"
    owner: "{{ ssh_connect_user }}" 
    mode: 0644
  with_items:
    - ca-config.json
    - ca-csr.json
    - apiserver-csr.json
    - front-proxy-ca-csr.json
    - front-proxy-client-csr.json
    - admin-csr.json
    - manager-csr.json
    - scheduler-csr.json