---
# Kubernetes
## ********************************************************************************************************************************

- name: Create Kubernetes WorkDirs
  shell: "mkdir -p {{ kubernetes_etc_dirs }} {{ kubernetes_pki_dirs }} {{ kubernetes_manifests_dirs }}"

- shell: "chown {{ ssh_connect_user }} {{ kubernetes_etc_dirs }} {{ kubernetes_pki_dirs }} {{ kubernetes_manifests_dirs }}"

- name: Create Kubelet WorkDirs
  shell: "mkdir -p {{ kubernetes_etc_dirs }} {{ kubelet_work_dirs }}"

- shell: "chown {{ ssh_connect_user }} {{ kubelet_work_dirs }}"

# Etcd
## ********************************************************************************************************************************

- name: Create Etcd WorkDirs
  shell: "mkdir -p {{ etcd_ssl_dirs }} {{ etcd_data_dirs }}"

- shell: "chown {{ ssh_connect_user }} {{ etcd_ssl_dirs }} {{ etcd_data_dirs }}"

# System
## ********************************************************************************************************************************

- name: Create Kubelet Systemd ConfigDirs
  shell: "mkdir -p {{ systemd_etc_dirs }}kubelet.service.d/"

- shell: "chown {{ ssh_connect_user }} {{ systemd_etc_dirs }}kubelet.service.d/"

# System
## ********************************************************************************************************************************

- name: Copy CFSSL Kubernetes Json Files
  copy:
    src: roles/kubernetes-default/files/kubelet-csr.json
    dest: "{{ kubernetes_pki_dirs }}kubelet-csr.json"
    owner: "{{ ssh_connect_user }}" 
    mode: 0644